#include <nds.h>
#include <stdio.h>
#include <gl2d.h>

#include "cursorO.h"



CursorPointer* InitializeCursor() {
	CursorPointer *cursor_pointer = malloc(sizeof(CursorPointer));
    cursor_pointer->x = 0;
	cursor_pointer->y = 0;
	cursor_pointer->texture_id = 
		glLoadTileSet( cursor_pointer->textures,		// pointer to glImage array
					   16,					// sprite width
					   16,					// sprite height
					   16,					// bitmap width
					   16,					// bitmap height
					   GL_RGB256,			// texture type for glTexImage2D() in videoGL.h 
					   TEXTURE_SIZE_256,	// sizeX for glTexImage2D() in videoGL.h
					   TEXTURE_SIZE_256,	// sizeY for glTexImage2D() in videoGL.h
					   GL_TEXTURE_WRAP_S|GL_TEXTURE_WRAP_T|TEXGEN_OFF|GL_TEXTURE_COLOR0_TRANSPARENT, // param for glTexImage2D() in videoGL.h
					   256,					// Length of the palette to use (256 colors)
					   (u16*)cursorPal,		// Load our 256 color tiles palette
					   (u8*)cursorBitmap		// image data generated by GRIT
					 );

	return cursor_pointer;
}

void CursorLogic(CursorPointer* cursor_pointer, int key, int prev_keys) {
    if ((key & KEY_Y) && !(prev_keys & KEY_Y)) {
			cursor_pointer->x -= 16;
		}
		if ((key & KEY_A) && !(prev_keys & KEY_A)) {
			cursor_pointer->x += 16;
		}
		if ((key & KEY_B) && !(prev_keys & KEY_B)) {
			cursor_pointer->y += 16;
		}
		if ((key & KEY_X) && !(prev_keys & KEY_X)) {
			cursor_pointer->y -= 16;
		}

		if (cursor_pointer->x < 0) {
			cursor_pointer->x = 0;
		}
		if (cursor_pointer->y < 0) {
			cursor_pointer->y = 0;
		}
}

void DrawCursor(CursorPointer* cursor_pointer, Camera* camera) {
	glSprite( cursor_pointer->x - camera->x,
			  cursor_pointer->y - camera->y,
			  GL_FLIP_NONE,
			  &cursor_pointer->textures[0]
	);
}