/*======================================================================

   crono coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef PLAYER__H
#define PLAYER__H


#define PLAYER_BITMAP_WIDTH   512
#define PLAYER_BITMAP_HEIGHT  32
#define PLAYER_NUM_IMAGES   1


		//	Format:
		//	U,V,Width,Height



const unsigned int player_texcoords[] = {
 0, 0, 20, 30,				// 0
 0, 0, 20, 30,				// 1
 0, 0, 20, 30,				// 2
 0, 0, 20, 30,				// 3
 0, 0, 20, 30,				// 4
 0, 0, 20, 30,				// 5
 0, 0, 20, 30,				// 6
 0, 0, 20, 30,				// 7
 0, 0, 20, 30,				// 8
 0, 0, 20, 30,				// 9
 0, 0, 20, 30,				// 10
 0, 0, 20, 30,				// 11
 0, 0, 20, 30,				// 12
 0, 0, 20, 30,				// 13
 0, 0, 20, 30,				// 14
 0, 0, 20, 30,				// 15
 0, 0, 20, 30,				// 16
 0, 0, 20, 30,				// 17
 0, 0, 20, 30				// 18
};


#endif
